### ISSUE TITLE
Styletron v4

### ISSUE THREAD

**Issue by Ayc0** [astrada/bs-styletron-react#1]
Do you plan to support the v4 of styletron ?

**Comment by astrada** [comment]
I can try to work on it, but the problem is that styletron v4 uses `$`-prefixed properties that cause syntax issues in ReasonML (you cannot access them via the `##` operator and you cannot use them in jsx).

**Comment by astrada** [comment]
I just published v0.3.0 that uses styletron-react v4. Check this [example](https://github.com/astrada/bs-styletron-react-examples/blob/master/src/Link.re) to see how to use `$`-prefixed properties.
